const eras=[['Garage Electronics','1976','Workbench'],['Apple II Hardware','1977','Board Assembly'],['Software & Logic','1979','Code Lab'],['Xerox & GUI','1980','Research Visit'],['IBM Connections','1981','Business Lab'],['Manufacturing','1983','Production Floor'],['Macintosh Era','1984','Design Studio'],['Networks','1990','Network Room'],['Mobile Systems','2007','Device Lab'],['Future Lab','2026','Prototype Studio']];
const topics=[
['Ohm’s law','A 5 V rail drives a 250 Ω load. What current flows?','20 mA','2 mA','200 mA','I=V/R=5/250=.02 A = 20 mA.'],
['Series resistance','Two 220 Ω resistors are in series. Total resistance?','440 Ω','110 Ω','220 Ω','Series resistances add.'],
['Parallel resistance','Two equal 1 kΩ resistors are parallel. Equivalent?','500 Ω','2 kΩ','1 kΩ','Two equal parallel resistors halve the resistance.'],
['Power','A component uses 5 V at 2 A. Power?','10 W','2.5 W','7 W','P=VI.'],
['Binary','What is decimal 13 in binary?','1101','1011','1110','8+4+1 = 13.'],
['Logic','An AND gate outputs 1 when…','both inputs are 1','either input is 1','both inputs are 0','AND requires both inputs high.'],
['Capacitance','What does a capacitor primarily store?','electric charge','program instructions','magnetic poles','Capacitance describes stored charge per volt.'],
['Clock','Why does a CPU clock matter?','It coordinates state changes','It raises screen brightness','It stores files','Clock edges synchronize digital operations.'],
['Ground','Circuit ground is primarily…','a common reference potential','always literal Earth','a cooling wire','Ground provides the circuit voltage reference.'],
['Debugging','Best first step when a board will not power?','verify supply rails safely','replace every IC','increase voltage','Measure before replacing components.']];
const objects=[['🔌','Power rail'],['⚡','Capacitor'],['〰️','Resistor'],['🔲','CPU'],['🧠','Memory'],['⌨️','Keyboard'],['📟','Display'],['📐','Schematic'],['☎️','Business call'],['📄','Agreement'],['🖧','Network'],['🧰','Tool kit']];
let n=0,xp=0,locked=false;
const $=id=>document.getElementById(id);
function mission(){const level=Math.floor(n/10),t=topics[n%10],e=eras[level];locked=false;$('level').textContent=`LEVEL ${level+1}`;$('score').textContent=`${xp} XP`;$('era').textContent=e[0];$('year').textContent=e[1];$('sceneName').textContent=e[2];$('missionCount').textContent=`Mission ${n+1} / 100`;$('bar').style.width=`${n+1}%`;$('question').textContent=t[1];$('lesson').textContent=`${t[0]} • Find the relevant part of the scene, then solve the engineering check.`;$('feedback').textContent='Tap the scene object that best fits the mission.';$('next').disabled=true;$('answers').innerHTML='';draw(t);}
function draw(t){const board=$('board');board.innerHTML='';objects.forEach((o,i)=>{const b=document.createElement('button');b.className='hotspot';b.innerHTML=`<strong>${o[0]}</strong>${o[1]}`;b.onclick=()=>{if(locked)return;const good=(n%10<4&&[2,0,3,7].includes(i))||(n%10>=4&&i===3)||(n%10===6&&i===1)||(n%10===8&&i===0)||(n%10===9&&i===11);if(good){b.classList.add('hit');$('feedback').textContent=`Scene unlocked: ${o[1]}. Now solve the check.`;answers(t)}else{b.classList.add('miss');setTimeout(()=>b.classList.remove('miss'),250);$('feedback').textContent=`${o[1]} is useful, but inspect another part for this mission.`}};board.appendChild(b)})}
function answers(t){if($('answers').children.length)return;[t[2],t[3],t[4]].sort(()=>Math.random()-.5).forEach(a=>{const b=document.createElement('button');b.className='answer';b.textContent=a;b.onclick=()=>{if(locked)return;locked=true;if(a===t[2]){b.classList.add('correct');xp+=100;$('feedback').textContent=`Correct. ${t[5]} +100 XP`}else{b.classList.add('wrong');$('feedback').textContent=`Not quite. ${t[5]}`;[...$('answers').children].find(x=>x.textContent===t[2])?.classList.add('correct')}$('score').textContent=`${xp} XP`;$('next').disabled=false};$('answers').appendChild(b)})}
$('next').onclick=()=>{if(n<99){n++;mission()}else{$('feedback').textContent='Campaign complete — prototype certified.';$('next').disabled=true}};
$('share').onclick=async()=>{const data={title:'Pirates of Silicon Valley — Interactive Computer Lab',text:'Build computers through 100 technical missions.',url:location.href};if(navigator.share)try{await navigator.share(data);return}catch(e){}window.open('https://twitter.com/intent/tweet?text='+encodeURIComponent(data.text)+'&url='+encodeURIComponent(data.url),'_blank')};
$('levels').innerHTML=eras.map((e,i)=>`<div class="levelCard"><b>${i+1}. ${e[0]}</b>${e[1]} • 10 missions</div>`).join('');mission();